name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-scripts --no-interaction --prefer-dist

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm install

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=<your_project_key> \
            -Dsonar.host.url=http://100.28.167.178:9000 \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.language=php,js,css \
            -Dsonar.sources=.
